### ISSUE TITLE
Crear clases Tabla, Tarea y Usuario

### ISSUE THREAD

**Issue by macheitor** [qfluis/ITAcademy_node_S3.3-S4-S5_REST_SERVER-JWT-BD-SOCKETS#10]
Crear las clases de Tabla, Tarea y Usuario en diferentes ficheros con los atributos y los metodos iniciales vacios (solo estructura)

**Comment by qfluis** [comment]
# Clase Tabla
mirar https://github.com/qfluis/ITAcademy_node_S4-S5_REST_SERVER-JWT-BD-SOCKETS/issues/8
# Clase User (podría estar dentro de Tabla como array de strings ¿?)
nombre user
# Clase Tarea
id
estado (TODO, ONGOING, DONE)
titulo
fecha_creación
fecha_inicio
fecha_fin
usuario
